// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArteNaPraia.Migrations
{
    [DbContext(typeof(ArteNaPraiaContext))]
    partial class ArteNaPraiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ArteNaPraia.Models.Arte", b =>
                {
                    b.Property<int>("IdArte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdArtista")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Preco")
                        .HasColumnType("float");

                    b.HasKey("IdArte");

                    b.HasIndex("IdArtista");

                    b.ToTable("Arte");
                });

            modelBuilder.Entity("ArteNaPraia.Models.Artista", b =>
                {
                    b.Property<int>("IdArtista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ChavePix")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdArtista");

                    b.ToTable("Artista");
                });

            modelBuilder.Entity("ArteNaPraia.Models.Arte", b =>
                {
                    b.HasOne("ArteNaPraia.Models.Artista", "Artista")
                        .WithMany("Artes")
                        .HasForeignKey("IdArtista")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("ArteNaPraia.Models.Artista", b =>
                {
                    b.Navigation("Artes");
                });
#pragma warning restore 612, 618
        }
    }
}
